#!/usr/bin/env bash

DIR="$HOME/myenv"

source "$DIR/lib/detect_distro"
source "$DIR/lib/print_line"
source "$DIR/lib/run_scripts"
source "$DIR/lib/stow_dotfiles"
source "$DIR/lib/update_packages"
source "$DIR/lib/install_zsh_ohmyzsh"

detect_distro
update_packages
run_scripts

print_line "Stowing dotfiles"
stow_dotfiles

print_line "Installing zsh with ohmyzsh"
install_zsh_ohmyzsh

print_line "Foi meu chapa =)"
