#!/usr/bin/env bash

DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"
LIB_DIR="$DIR"/lib

for FILE in "$LIB_DIR"/*; do
  source "$FILE"
done

detect_distro
update_packages
run_scripts

print_line "Stowing dotfiles"
stow_dotfiles

print_line "Installing zsh with ohmyzsh"
install_zsh_ohmyzsh
