#!/usr/bin/env bash

source "$DIR/lib/print_line"

SCRIPTS_DIR="$DIR/scripts"
cd "$DIR"

run_scripts() {
  if [[ -d "$SCRIPTS_DIR" ]]; then
    for script in "$SCRIPTS_DIR"/"$DIST"/*; do
      print_line "Executing $script..."
      sudo chmod +x "$script"
      sh "$script"
    done
  else
    echo "Scripts dir not found."
    exit 1
  fi
}
