#!/usr/bin/env bash

update_packages() {
  if [[ "$DIST" == "fedora" ]]; then
    echo "Dist: $DIST"
    sudo dnf update -y
  elif [[ "$DIST" == "ubuntu" ]]; then
    sudo apt update -y && sudo apt upgrade -y
  else
    echo "Dist: $DIST not configured."
    exit 1
  fi
}
